<a href="https://colab.research.google.com/github/dramitprabhumd-cpu/Python_Phoenix/blob/main/numpy/NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## 15/01/2026 Creating an Array

In NumPy, when **creating a multidimensional array**, the entire structure needs to be wrapped in a **single list** (or tuple).<br>
e.g. b = np.array([[1, 2, 3],[4, 5, 6]]), i.e. tuple of list of lists

In [ ]:
import numpy as np
# 1D array (1 x 3)
array1D = np.array([1, 2, 3])

# 2D array (2 x 3) - floats
array2D = np.array([[1.2, 2.4, 3.6],[4.8, 6.0, 7.2]])

#3D array (3 x 3)
array3D = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print(array1D)
print(array2D)
print(array3D)

[1 2 3]
[[1.2 2.4 3.6]
 [4.8 6.  7.2]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


##.ndim
**.ndim** - gets dimension of an array (1D/2D/3D...)


In [ ]:
import numpy as np
# 1D array (1 x 3)
array1D = np.array([1, 2, 3])

# 2D array (2 x 3) - floats
array2D = np.array([[1.2, 2.4, 3.6],[4.8, 6.0, 7.2]])

#3D array (3 x 3)
array3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# Get Dimension
print(array1D.ndim)
print(array2D.ndim)
print(array3D.ndim)

1
2
3


##.shape
**.shape** - gives a vector of dimension of array (e.g.(2,3) for 2x3)

In [ ]:
import numpy as np
# 1D array (1 x 3)
array1D = np.array([1, 2, 3])

# 2D array (2 x 3) - floats
array2D = np.array([[1.2, 2.4, 3.6],[4.8, 6.0, 7.2]])

# pseudo3D array (3 x 3)
array3D = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

#true 3D array
arrayTrue3D = np.array([[[1,2],
                         [3,4]],
                        [[5,6],
                         [7,8]]])
# Get Shape
print(array1D.shape)
print(array2D.shape)
print(array3D.shape)
print(arrayTrue3D.shape)

(3,)
(2, 3)
(3, 3)
(2, 2, 2)


##dtype
**.dtype** - short for *data type* - tells what type of data is stored inside the array.<br>
Unlike standard Python lists, which can hold a mix of strings, integers, and objects, NumPy arrays are **homogeneous**. This means every element in the array must have the same data type and occupy the same amount of memory.<br>
**Common Data Types:**<br>


1.   Int  (5, -10, 100) - dtype: int32 or int64
2.   Float (3.14, 2.0) - dtype: float64
3. Boolean (True, False) - dtype: bool_
4. Complex nos. (1 + 2j) - dtype: complex128
5. Unicode string ('hello') - dtype: <U10



In [ ]:
import numpy as np
# 1D array (1 x 3)
array1D = np.array([1, 2, 3])

# 2D array (2 x 3) - floats
array2D = np.array([[1.2, 2.4, 3.6],[4.8, 6.0, 7.2]])

#3D array (3 x 3)
array3D = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
# Get data type
print(array1D.dtype)
print(array2D.dtype)

int64
float64


You can force a specific data type to save memory. <br>
For example, if you know your numbers will always be **small**, you can use *int8* instead of the default *int64*.

In [ ]:
import numpy as np
# 1D array (1 x 3) data type int8
array1DInt8 = np.array([1, 2, 3], dtype='int8')
print(array1DInt8.dtype)

int8


##itemsize
**.itemsize** - tells you the physical space (in bytes) that each individual element occupies in your computer's memory.<br>
*Think of it this way: **.dtype** is the label on the box, and **.itemsize** is the measurement of the box.*<br>
**Relation to dtype:**


1. int8 / uint8 = 8 bits = 1 byte
2. float32 / int32 = 32 bits = 4 bytes
3. float64 / int64 = 64 bits = 8 bytes
4. complex128 = 128 bits = 16 bytes



In [ ]:
import numpy as np
# 1D array (1 x 3)
array1D = np.array([1, 2, 3])

# 1D array (1 x 3) data type int8
array1DInt8 = np.array([1, 2, 3], dtype='int8')

# 2D array (2 x 3) - floats
array2D = np.array([[1.2, 2.4, 3.6],[4.8, 6.0, 7.2]])

print(array1D.dtype, array1D.itemsize)
print(array1DInt8.dtype, array1DInt8.itemsize)
print(array2D.dtype, array2D.itemsize)

int64 8
int8 1
float64 8


##.size
**.size** - gives the number of elements in an array

In [ ]:
import numpy as np
# 1D array (1 x 3)
array1D = np.array([1, 2, 3])

# 2D array (2 x 3) - floats
array2D = np.array([[1.2, 2.4, 3.6],[4.8, 6.0, 7.2]])

#3D array (3 x 3)
array3D = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Get Size - No. of elements
print(array1D.size)
print(array2D.size)
print(array3D.size)

3
6
9


So, one way to get **total memory size** of an array by (.itemsize * .size)


In [ ]:
import numpy as np
# 1D array (1 x 3)
array1D = np.array([1, 2, 3])

# 2D array (2 x 3) - floats
array2D = np.array([[1.2, 2.4, 3.6],[4.8, 6.0, 7.2]])

#3D array (3 x 3)
array3D = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
memoryA1D = array1D.itemsize * array1D.size
memoryA2D = array2D.itemsize * array2D.size
print(memoryA1D)
print(memoryA2D)


24
48


##.nbytes
**.nbytes** - directly gives the memory size of an array

In [ ]:
import numpy as np
# 1D array (1 x 3)
array1D = np.array([1, 2, 3])

# 2D array (2 x 3) - floats
array2D = np.array([[1.2, 2.4, 3.6],[4.8, 6.0, 7.2]])

#3D array (3 x 3)
array3D = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Get Memory Size directly
print(array1D.nbytes)
print(array2D.nbytes)
print(array3D.nbytes)

24
48
72


## 18/01/2026 - Accessing / Changing Specific Elements/Rows/Columns

##Accessing an element
**Notation:** (*row*, *column*)<br>
*Index from zero* <br>
**Can use negative (-) notation too!!**<br>
[i.e. last element is -1]

In [ ]:
import numpy as np
a2by7 = np.array([[1, 2, 3, 4, 5, 6, 7],
                  [8, 9, 10, 11, 12, 13, 14]])
print(a2by7)
print(f'Shape of a2by7 matrix: {a2by7.shape}')

# Access element 13 i.e row = 1 and column = 5 (Starting at 0)
print(a2by7[1, 5])

# Access element 6, using negative notation: row = 0 & column = -2
print(a2by7[0, -2])

## Getting specific Row / Column
**Notation:**<br>
*Row-* [row, :] i.e all columns of the row<br>
*Column-* [:, column] i.e. all rows of the column

In [ ]:
import numpy as np
a2by7 = np.array([[1, 2, 3, 4, 5, 6, 7],
                  [8, 9, 10, 11, 12, 13, 14]])
print(a2by7)
print(f'Shape of a2by7 matrix: {a2by7.shape}')
print()
# Getting 2nd row (index = 1)
print(a2by7[1, :])
print()
# Getting last column (index = -1)
print(a2by7[:, -1])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
Shape of a2by7 matrix: (2, 7)

[ 8  9 10 11 12 13 14]

[ 7 14]


In [ ]:
import numpy as np
a3by7 = np.array([[1,2,3,4,5,6,7],
                  [8,9,10,11,12,13,14],
                  [15,16,17,18,19,20,21]])
print(a3by7)
print()
print(f'Shape of a3by7 matrix: {a3by7.shape}')
print()
# Getting from Rows 1 & 2 (3 exclusive) Column 5 (index 4)
print(a3by7[1:3, 4])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]

Shape of a3by7 matrix: (3, 7)

[12 19]


## Getting a bit Fancy
*Getting specific series of elements*<br>
**Notation:** [StartIndex : EndIndex : Step]<br>
*EndIndex is **EXCLUSIVE***<br>
**Special Cases**<br>
1. **StartIndex - blank**[row, :end:step]: starts at index 0
2. **EndIndex - blank** [row, start::step]:
ends at last element
3. **Both blank** [row, ::step]:
gives complete row *(if step = 1)* or flips the row *(if step = -1)*

In [ ]:
import numpy as np
a2by7 = np.array([[1, 2, 3, 4, 5, 6, 7],
                  [8, 9, 10, 11, 12, 13, 14]])
print(a2by7)
print(f'Shape of a2by7 matrix: {a2by7.shape}')

# Getting elements 2, 4, 6
print(a2by7[0, 1:6:2])
# [Row=0, Start=1 : End before 6(i.e. 5) : Step = 2 (i.e. alternate)]

# Getting 12, 13, 14
print(a2by7[1, -3::1])

# Getting a flipped row
print(a2by7[0, ::-1])

## Altering an element

In [ ]:
import numpy as np
a2by7 = np.array([[1, 2, 3, 4, 5, 6, 7],
                  [8, 9, 10, 11, 12, 13, 14]])
print(a2by7)
print(f'Shape of a2by7 matrix: {a2by7.shape}')
print()

# Changing element 4 to 999
a2by7[0, 3] = 999
print(a2by7)

## Altering a Column / Row

In [ ]:
import numpy as np
a2by7 = np.array([[1, 2, 3, 4, 5, 6, 7],
                  [8, 9, 10, 11, 12, 13, 14]])
print(a2by7)
print(f'Shape of a2by7 matrix: {a2by7.shape}')
print()

# Changing 3rd column to 999
a2by7[:, 2] = (999, 999)
print(a2by7)

# Changing 1st row to 1
a2by7[0, :] = (1, 1, 1, 1, 1, 1, 1)
print(a2by7)
print()

# Changing middle 3 elements of 1st row to 0
a2by7[0, 2:5] = (0, 0, 0)
print(a2by7)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
Shape of a2by7 matrix: (2, 7)

[[  1   2 999   4   5   6   7]
 [  8   9 999  11  12  13  14]]
[[  1   1   1   1   1   1   1]
 [  8   9 999  11  12  13  14]]

[[  1   1   0   0   0   1   1]
 [  8   9 999  11  12  13  14]]


## Working with 3D Arrays

In [ ]:
import numpy as np
# pseudo3D array (3 x 3)
array3D = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

#true 3D array
arrayTrue3D = np.array([[[1,2],
                         [3,4]],
                        [[5,6],
                         [7,8]]])
print(array3D)
print(array3D.ndim)
print()
print(arrayTrue3D)
print(arrayTrue3D.ndim)
print()

# Getting element 4 of pseudo 3D
print(array3D[1, 0])
print()
# Getting element 4 of true 3D - Farthest Square Bracket Outside
# Inside Pink[] 1st Blue[] (index 0),
    # Inside Blue[] 2nd yellow[] (index 1),
      # Inside yellow[] 2nd element (index 1)
       # Hence [0, 1, 1]
print(arrayTrue3D[0, 1, 1])
print()
print(arrayTrue3D[:, 1, :])
# Inside Pink[] all blue[]s (index :)
      # Inside both Blue[]s 2nd Yellow[]s (index 1)
       #  Inside both Yellow[]s all elements (index :)

arrayTrue3D[:, 0, :] = ([1,1],[0,0])
print(arrayTrue3D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3

4

4

[[3 4]
 [7 8]]
[[[1 1]
  [3 4]]

 [[0 0]
  [7 8]]]


## 19/01/2026 - Initializing Different Types of Arrays


## All Zeros Matrix
**np.zeros((tuple))**<br>
**Argument**: Either an *int* for 1D Or a *tuple* for **shape**


In [ ]:
import numpy as np
# All 0s matrix
print('0s 1x5 matrix')
print(np.zeros(5))
print()
print('0s 2D matrix')
print(np.zeros((2,3)))
print()
print('0s 3D matrix')
print(np.zeros((3, 2, 3)))
print()
print('0s 4D matrix')
print(np.zeros((2, 2, 2, 2)))

## All Ones Matrix
**np.ones((tuple))**<br>
**Argument**: Either an *int* for 1D Or a *tuple* for **shape**

In [ ]:
import numpy as np
print(np.ones((4,3,2)))

## Any Other Number Matrix
**np.full((tuple), n)**<br>
**Argument**:
1. Either an *int* for 1D Or a *tuple* for **shape**
2. The number to form matrix of.

In [ ]:
import numpy as np
print(np.full((2,2,1), 99))

## Any Other Number Matrix with Shape similar to Another Matrix
**np.full_like(matrix, number)**<br>
**Argument**:
1. Matrix to copy shape
2. Number to form matrix

In [ ]:
import numpy as np
arrayTrue3D = np.array([[[1,2],
                         [3,4]],
                        [[5,6],
                         [7,8]]])
print(arrayTrue3D)
print()
print(np.full_like(arrayTrue3D, 9))

## Random Decimal (0 to 1) Number Matrix
**np.random.rand(shape)**<br>
**Argument:** Shape of matrix<br>
*Unlike elsewhere where there are 2 parentheses, here shape inside **single** parenthesis*

In [ ]:
import numpy as np
print(np.random.rand(2,2,2))

[[[0.35415229 0.97192822]
  [0.28299188 0.62539686]]

 [[0.36245663 0.15190643]
  [0.59102285 0.18697773]]]


## Random Decimal Number Matrix - Copy Shape
**np.random.random_sample(Matrix.shape)**<br>
**Argument:** Matrix to copy


In [ ]:
import numpy as np
a2by7 = np.array([[1, 2, 3, 4, 5, 6, 7],
                  [8, 9, 10, 11, 12, 13, 14]])
print(np.random.random_sample(a2by7.shape))

## Random Integer Matrix
**np.random.randint(start, end, size = (m,n))<br>
**Arguments:**
1. *start* : start for random number
2. *end* : end for random number (exclusive)
3. *size* : shape of matrix

In [ ]:
import numpy as np
print(np.random.randint(0, 2, size=(2,2,3)))

##Identity Matrix
**np.identity(n)**<br>
Creates an Identity Matrix (n x n)

In [ ]:
import numpy as np
print(np.identity(5))

## 26/01/2026 - Repeating an Array to form A Matrix
**np.repeat(a, repeats, axis)**
**Arguments:**
1. **a**: Input array
2. **repeats**: How many times to repeat each element. This can be a -<br>
-  **single integer** - everyone repeats the same amount
- an array - each element gets a custom number of repeats
3. **axis**: The axis along which to repeat values.<br>
*By default, if no axis is given, the array is flattened.*

In [ ]:
import numpy as np
'''Simple 1D example'''
arr = ([1, 2, 3])
res = np.repeat(arr, 3)
print(res)

[1 1 1 2 2 2 3 3 3]


## 2D Repeats
When you move into **2D**, the *axis* parameter comes into picture:<br>
- **axis=0** : Repeats *Rows*.
- **axis=1** : Repeats *Columns*.

In [ ]:
import numpy as np
Mat2D = np.random.randint(5, size=(2, 2))
# Repeat ROWS twice
print(Mat2D)
print('Row Repeats: ')
print(np.repeat(Mat2D, 2, axis=0))
print()
print('Columns Repeats: ')
print(np.repeat(Mat2D, 2, axis=1))

## Custom Repetition
You can pass a *list* to the repeats argument to give each element its own "**personality**".

In [ ]:
import numpy as np
Mat1D = np.random.randint(5, size=(5))
Mat2D = np.random.randint(5, size=(2, 2))
print(Mat1D)
print()
print(Mat2D)
print()
print(np.repeat(Mat1D, [1,1,2,2,1]))
print()
print(np.repeat(Mat2D, [1,2], axis=1))
print()
print(np.repeat(Mat2D, [2,1], axis=0))

##Exercise!!
Creating a 5 x 5 Matrix with:
1. Boundaries of 1s
2. Inner layer of 0s
3. Centre of 9

In [ ]:
import numpy as np
myArray = np.ones([5,5])
print('Step 1: Creating All Ones 5x5 Matrix -')
print(myArray)
print()
print('Step 2: Changing 2nd - 4th rows\' 2nd - 4th elements to 0')
myArray[1:4, 1:4] = (0,0,0)
print(myArray)
print()
print('Step 3: Changing the centre to 9')
myArray[2, 2] = 9
print(myArray)

## 27/01/2026 Mathematical Operations

## Element-wise Arithmatic Operations
This is the "standard" math. If you add two arrays of the same shape, NumPy matches them up *index-by-index*.<br>
**Broadcasting**: If the shapes don't match (e.g., *adding a single number to an array*), NumPy "stretches" the smaller one to fit.

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([4, 3, 2])

print(f'a + b = {a + b}')
print(f' a x b = {a * b}')
print(f'Exponentiation (a ^ c) = {a ** c}')

## Aggregations: Summary Stats
Aggregations take an array and boil it down to a single value (or a set of values along an axis).
- **np.sum(a)**: returns sum of all elements
- **np.mean(a)**: returns average of elements
- **np.median(a)**: returns the middle value
- **np.std(a)**: measures data spread (SD)
- **np.min(a)**: returns lowest elemnt
- **np.max(a)**: returns largest element
- **np.argmax(a)**: returns *index* of highest value<br>

In [ ]:
import numpy as np
a = np.random.randint(30, size=(12))
print(f'Starting Array: {a}')
print()
print(f'Sum of elements = {np.sum(a)}')
print(f'Average = {np.mean(a)}')
print(f'Middle value = {np.median(a)}')
print(f'Standard Deviation = {np.std(a)}')
print(f'Smallest Element = {np.min(a)}')
print(f'Largest Element = {np.max(a)}')
print(f'Index of Largest Element = {np.argmax(a)}')


## Using Aggregations with Matrices
**Pro Tip:** Use the axis parameter!!<br>
- **axis=0** performs the math down columns
- **axis=1** goes across rows

**Summary of Shape Change** for shape = (3,3):
- **np.sum(a)**: Scalar 1 value (*everything collapsed*)
- **np.sum(a, axis=0)**: 1 value per *column* (*rows* collapsed - adds elements of **each column**)
- **np.sum(a, axis=1)**: 1 value per *row* (*columns* collapsed - adds elements of **each row**)


In [ ]:
import numpy as np
b = np.random.randint(30, size=(4,4))
print('Starting Array: ')
print(b)
# no axis - collapses everything into 1 scalar value
print(f'Sum of all elements = {np.sum(b)}')
print(f'Average Value = {np.mean(b)}')
print()

# axis = 0 : collapses rows into single row
print(f'Sum of elements of each Column: {np.sum(b, axis=0)}')
print(f'Average value of each Column: {np.mean(b, axis=0)}')

#axis = 1 : collapses columns into a single column
print(f'Sum of elements of each Row: {np.sum(b, axis=1)}')
print(f'Average value of each Row: {np.mean(b, axis=1)}')

Starting Array: 
[[20 17 10  8]
 [17 24  5 18]
 [26  9  2  8]
 [28  1 22 11]]
Sum of all elements = 226
Average Value = 14.125

Sum of elements of each Column: [91 51 39 45]
Average value of each Column: [22.75 12.75  9.75 11.25]
Sum of elements of each Row: [55 64 45 62]
Average value of each Row: [13.75 16.   11.25 15.5 ]


## Understanding the AXIS
In NumPy, an **axis** is just a fancy word for a *dimension*.<br>
**The Filing Cabinet Analogy**
Imagine a physical filing cabinet:

- Axis 0 (Rows): Think of this as which drawer you open.
- Axis 1 (Columns): Once the drawer is open, this is which folder you pick from front to back.
- Axis 2 (Depth): If each folder has multiple pages, this is which page you look at.

**Visual Examples:**
- **1D** array [1,2,3] has one axis (*Axis 0*)(Its just a line of numbers).
- **2D** array (matrix) has 2 axes:


*   **Axis 0** - runs vertically down the rows (*no. of rows*)
*   **Axis 1** - runs horizontally across columns (*no. of columns*)





## 03/02/2026 Linear Algebra

## Matrix & Vector Product
**np.dot(arr1, arr2)**: The dot product of two arrays. <br>
*For 2D arrays* - it is matrix multiplication <br>
*For 1D* - it is the inner product.

In [ ]:
import numpy as np
a = np.full((2, 3), 3)
b = np.ones((3, 2))
print(a)
print()
print(b)
print()
print('a dot b = ')
print(np.dot(a, b))
print()
A = np.full((5,3,2), 2)
B = np.full((5,2,3), 3)
print(A)
print()
print(B)
print ('A dot B = ')
print(np.dot(A, B))

**np.matmul(mtx1, mtx2)**<br>
This is same as **mtx1 @ mtx2**

In [1]:
import numpy as np
A = np.full((5,2), 3)
B = np.full((2,3), 2)
print(A)
print()
print(B)
print()
print(np.matmul(A, B))
print()
print(A@B)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]

[[2 2 2]
 [2 2 2]]

[[12 12 12]
 [12 12 12]
 [12 12 12]
 [12 12 12]
 [12 12 12]]

[[12 12 12]
 [12 12 12]
 [12 12 12]
 [12 12 12]
 [12 12 12]]


## Find the Determinant
**np.linalg.det(mtx)**

In [ ]:
import numpy as np
A = np.identity(3)
print(f'Determinant: {np.linalg.det(A)}')

Determinant: 1.0
